### ISSUE TITLE
error while computing laplacians

### ISSUE THREAD

**Issue by federicomalizia** [HGX-Team/hypergraphx#14]
after updating to 1.4.2 i got the error:

TypeError: binary_incidence_matrix() takes from 1 to 2 positional arguments but 3 were given

**Comment by FraLotito** [comment]
Can you please share the code that gives you an error?

**Comment by federicomalizia** [comment]
edge_list = [[0,7],[1,2],[1,7],[2,7],[3,7],[4,7],[5,7],[6,7],[1,2,7],[4,5,6],[4,5,7],[4,6,7],[5,6,7],[4,5,6,7]]
hypergraph = Hypergraph(edge_list)

laplacians = laplacian_matrices_all_orders(hypergraph)

**Comment by FraLotito** [comment]
Thanks for reporting this. The error should be fixed now, I've published an update. In a couple of minutes it should be available to install

**Comment by FraLotito** [comment]
I confirm that the update is now available with version 1.5

**Comment by federicomalizia** [comment]
via pip i can only get version 1.4.3

**Comment by FraLotito** [comment]
Sorry, my fault. Should be ok now
