### ISSUE TITLE
`linalg.hye_list_to_binary_incidence()` related tests are failing

### ISSUE THREAD

**Issue by ab1nash** [HGX-Team/hypergraphx#19]
The tests related to the function `linalg.hye_list_to_binary_incidence()` are failing. 

I suspect that this has something to do with [this](https://github.com/HGX-Team/hypergraphx/blob/8c0b8edce802c10417c555addf1d4d3536292eeb/hypergraphx/linalg/linalg.py#L45) part of the function.

**Comment by ab1nash** [comment]
On a related note, it would be ideal to have an automated testing pipeline for every PR

**Comment by FraLotito** [comment]
Yes, thank you for the suggestion! It would be very useful to have a testing pipeline, but we have not invested time there yet

**Comment by FraLotito** [comment]
Hi, tests are ok now. Working on a testing pipeline
