### ISSUE TITLE
Initilization of community number K for Hy-MMSBM model

### ISSUE THREAD

**Issue by mgao97** [HGX-Team/hypergraphx#27]
Hi~

I have one question about how to initialize the number of communities K for the Hy-MMSBM method. What if one does not know the potential communities or ground truth of community information? 

Thank you in advance and I look forward to your suggestions for such a situation.

**Comment by nickruggeri** [comment]
Hi @mgao97,

this is more of a "scientific" question than a "coding" one.

In general the number of communities `K` needs to be chosen via model selection techniques. 
We briefly touch upon the topic in the paper
https://www.science.org/doi/10.1126/sciadv.adg9159
both in the main text and appendix H. 

You can look at link prediction measures, such as the AUC or other measures of fit quality, on a test set consisting of some held-out hyperedges that are hidden from the model at training time. 
Other model selection techniques such as BIC or AIK are also feasible, but they are conjectured not to be very reliable on statical problems on networks. 

Hope this helps!

**Comment by mgao97** [comment]
Hi～

Thank you for your message and suggestions! 

Yes, you are right. It is clear to me.
