### ISSUE TITLE
When will you release the dataset?

### ISSUE THREAD

**Issue by jeongwhanchoi** [HGX-Team/hypergraphx#29]

**Comment by FraLotito** [comment]
Hi! I have fixed some bugs in load and save modules, I need to reformat the dataset such that they can be loaded easily in the library. I should be able to upload face-to-face interaction datasets by tomorrow, and release day-by-day the other domains (co-authorship, co-voting, etc). Let me know if you have priority on some specific data.

**Comment by FraLotito** [comment]
Hi! Our data repo is now public with the first datasets: https://github.com/HGX-Team/data

We will keep populating it with more datasets.

**Comment by jeongwhanchoi** [comment]
Thank you for making your first dataset public.
