### ISSUE TITLE
Division by Zero Error in norm_vector Function

### ISSUE THREAD

**Issue by GiovanniForlenza** [HGX-Team/hypergraphx#34]
I am experiencing a division by zero error using the norm_vector function in the library. The error occurs when M results in zero, causing a ZeroDivisionError exception. This can happen if the input vector a consists of only zeros.
Modify norm_vector to handle the case when M is 0.
Thank you for your attention!

**Comment by FraLotito** [comment]
Thank you Giovanni! I've fixed the issue, it will be added to the next release.
