### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by wsamoy** [HGX-Team/hypergraphx#4]
Dear,

When performing:

1 pip install hypergraphx
2 import hypergraphx

I get following error: "ImportError: cannot import name 'core' from partially initialized module 'hypergraphx' (most likely due to a circular import) (C:\Users\32486\anaconda3\lib\site-packages\hypergraphx\__init__.py)"

I have tried cloning the git repository and installing that way but the error remains. I have no idea what goes wrong as when performing the pip install all requirements are satisfied. 

Any help is welcome.

Kind regards,
Ward

(This is my first ever issue submitted in github so my apologies if it does not follow convention)
![Pic1](https://user-images.githubusercontent.com/130225907/230720968-e3ec0735-daae-4d8d-b74a-e1c5767e6729.PNG)

**Comment by q923397935** [comment]
You can download github files to run on your local computer

**Comment by FraLotito** [comment]
Hi!

The issue is solved as of now, we have updated the instructions to install the library.
