### ISSUE TITLE
method get_adj_node not found

### ISSUE THREAD

**Issue by francescoboldrin** [HGX-Team/hypergraphx#7]
I was trying to use the s_betweenness function using as input the highschool data set for hypergraph, when i tried to launch the program it gave an error in function line_graph(h: Hypergraph, distance='intersection', s=1, weighted=False) in projections.py script.
Reporting that 'Hypergraph' has no attribute 'get_adj_nodes()' .
RunTime error in line 125, projections.py script

**Comment by FraLotito** [comment]
Thank you for reporting this!

I have fixed the issue
